version: '3'
services:
  mongo_db:
    container_name: mongo_db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./users.json:/app/resources/users.json
      - ./docker-entrypoint-initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: test
  mongo_admin:
    container_name: mongo_admin
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongo_db
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo_db:27017/
  meilisearch:
    image: "getmeili/meilisearch:latest"
    ports:
      - "7720:7700"
    environment:
      - MEILI_NO_ANALYTICS=false
      - MEILI_NO_SENTRY=true
    volumes:
      - ./users_meili.json:/app/resources/users.json
      - ./movies.json:/app/resources/movies.json
    environment:
      MEILI_MASTER_KEY: "masterKey"
      #springboot:
      # build:
      #  context: .
      # dockerfile: Dockerfile
    #image: springboot-sta-ines/latest