spring:
  data:
    mongodb:
      uri: 'mongodb://root:example@localhost:27017/test?authSource=admin'
      auto-index-creation: true
  servlet:
    multipart:
      max-file-size: 5000KB
      max-request-size: 5000KB
  ## Hibernate properties
  #spring.jpa.hibernate.use-new-id-generator-mappings=false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  endpoints:
    web:
      cors:
        allowedOrigins:
          - localhost
          - http://localhost:8888
          - http://localhost:4200
        allowedMethods:
          - GET
          - POST
          - DELETE
          - PUT
          - OPTIONS
        allowed-origin-patterns: "*"
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html


