spring:
  data:
    mongodb:
      uri: 'mongodb://root:example@localhost:27017/test?authSource=admin'
      auto-index-creation: true
  servlet:
    multipart:
      max-file-size: 5000KB
      max-request-size: 5000KB
## Hibernate properties
#spring.jpa.hibernate.use-new-id-generator-mappings=false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  security:
    user:
      name: admin
      password: admin
    oauth2:
      authorizationserver:
        client:
            client-id: client
            client-secret: secret
            authorized-grant-types: authorization_code,refresh_token,password,client_credentials
            scope: read,write
            autoapprove: true
            redirect-uri: http://localhost:8080/login/oauth2/code/custom
            access-token-validity-seconds: 60
            refresh-token-validity-seconds: 120
management:
  endpoints:
    web:
      cors:
        allowed-origins: "localhost"
        allowed-methods: "GET, PUT, POST, DELETE, OPTIONS"
        allow-credentials: off
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html



